#!/usr/bin/env bash

set -e

DEFAULT_HOST="uranium"

if [ -z ${1+x} ]
  then CONFIG="config/install.${DEFAULT_HOST}.yml"
else
  CONFIG="config/install.${1}.yml"
fi

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}"
