install dnsmasq
install gnupg2
install macvim
install mercurial

install mysql
services start mysql

install node
install python
install rbenv
install ruby-build
install vim
install zsh

install brew-cask

tap thoughtbot/formulae
install rcm

tap homebrew/science


tap josegonzalez/php
install php55

tap phinze/cask
