- clean: ['~']

- link:
    ~/.aliases: aliases
    ~/.atom: atom/
    ~/.config/keybase: keybase/
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.rbenv: rbenv/
    ~/.rspec: rspec
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.zsh: zsh/
    ~/.zshenv: zshenv
    ~/.zshrc: zshrc
    ~/.aliases.local: uranium.local/aliases.local
    ~/.gitconfig.local: uranium.local/gitconfig.local
    ~/.gitignore_global: uranium.local/gitignore_global
    ~/.zshenv.local: uranium.local/zshenv.local
    ~/.zshrc.local: uranium.local/zshrc.local

- shell:
  -
    - git submodule update --init --recursive
    - Installing/updating submodules
  -
    command: ./uranium.local/linkdirs.sh
    stdout: true
