install dnsmasq
install gnupg2
install macvim
install mercurial
install git

install mysql
services start mysql

install node
install python
install rbenv
install ruby-build
install vim
install zsh

tap caskroom/homebrew-cask
install brew-cask

tap thoughtbot/formulae
install rcm

tap homebrew/science


tap josegonzalez/php
install php55
